#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

# --- Configuration ---
NS=${NS:-openshift-storage}
CEPH_CLUSTER_NAME=${CEPH_CLUSTER_NAME:-ocs-storagecluster-cephcluster}
STORAGE_CLASS=${STORAGE_CLASS:-ocs-storagecluster-ceph-rbd-encrypted}
CSI_KMS_CONFIGMAP=${CSI_KMS_CONFIGMAP:-csi-kms-connection-details}
ENV_FILE="${SCRIPT_DIR}/.env"

# --- Auto-detect HPCS config from the cluster ---

detect_hpcs_config() {
  log_info "Auto-detecting HPCS configuration from cluster..."

  local security_json
  security_json=$($(kube_cmd) -n "${NS}" get cephcluster "${CEPH_CLUSTER_NAME}" \
    -o jsonpath='{.spec.security}' 2>/dev/null) || log_fatal "CephCluster '${CEPH_CLUSTER_NAME}' not found in namespace ${NS}"

  local detected_instance_id detected_url detected_api_key detected_token_secret

  detected_instance_id=$(echo "${security_json}" | jq -r '.kms.connectionDetails.IBM_KP_SERVICE_INSTANCE_ID // empty')
  detected_url=$(echo "${security_json}" | jq -r '.kms.connectionDetails.IBM_KP_BASE_URL // empty')
  detected_token_secret=$(echo "${security_json}" | jq -r '.kms.tokenSecretName // empty')

  if [[ -z "${detected_instance_id}" ]]; then
    log_fatal "Could not detect IBM_KP_SERVICE_INSTANCE_ID from CephCluster CR"
  fi
  if [[ -z "${detected_url}" ]]; then
    log_fatal "Could not detect IBM_KP_BASE_URL from CephCluster CR"
  fi
  if [[ -z "${detected_token_secret}" ]]; then
    log_fatal "Could not detect tokenSecretName from CephCluster CR"
  fi

  detected_api_key=$($(kube_cmd) -n "${NS}" get secret "${detected_token_secret}" \
    -o jsonpath='{.data.IBM_KP_SERVICE_API_KEY}' 2>/dev/null | base64 -d) || true
  if [[ -z "${detected_api_key}" ]]; then
    log_fatal "Could not read IBM_KP_SERVICE_API_KEY from secret '${detected_token_secret}'"
  fi

  # Detect HPCS root key ID from CSI KMS config
  local detected_key_id=""
  local sc_json kms_id kms_entry kms_secret_name
  sc_json=$($(kube_cmd) get storageclass "${STORAGE_CLASS}" -o json 2>/dev/null) || true
  if [[ -n "${sc_json}" ]]; then
    kms_id=$(echo "${sc_json}" | jq -r '.parameters.encryptionKMSID // empty')
    if [[ -n "${kms_id}" ]]; then
      kms_entry=$($(kube_cmd) -n "${NS}" get configmap "${CSI_KMS_CONFIGMAP}" \
        -o jsonpath="{.data.${kms_id}}" 2>/dev/null) || true
      if [[ -n "${kms_entry}" ]]; then
        kms_secret_name=$(echo "${kms_entry}" | jq -r '.IBM_KP_SECRET_NAME // empty')
        if [[ -n "${kms_secret_name}" ]]; then
          detected_key_id=$($(kube_cmd) -n "${NS}" get secret "${kms_secret_name}" \
            -o jsonpath='{.data.IBM_KP_CUSTOMER_ROOT_KEY}' 2>/dev/null | base64 -d) || true
        fi
      fi
    fi
  fi

  if [[ -z "${detected_key_id}" ]]; then
    log_warn "Could not auto-detect HPCS_KEY_ID from CSI KMS config. Set it manually."
  fi

  echo ""
  log_info "=== Detected HPCS Configuration ==="
  log_info "  Instance ID:    ${detected_instance_id}"
  log_info "  URL:            ${detected_url}"
  log_info "  Token secret:   ${detected_token_secret}"
  log_info "  API key:        ${detected_api_key:0:8}...${detected_api_key: -4}"
  log_info "  Root key ID:    ${detected_key_id:-<not detected>}"
  echo ""

  read -rp "Write these values to ${ENV_FILE}? (yes/no): " confirm
  if [[ "${confirm}" != "yes" ]]; then
    log_info "Skipped writing to .env. Set HPCS_* variables manually before proceeding."
    return
  fi

  write_env_values "${detected_instance_id}" "${detected_url}" "${detected_api_key}" "${detected_key_id}"
}

write_env_values() {
  local instance_id="$1" url="$2" api_key="$3" key_id="${4:-}"

  if [[ -f "${ENV_FILE}" ]]; then
    # Update existing values or append missing ones
    local updated=false

    local pairs=(
      "HPCS_INSTANCE_ID:${instance_id}"
      "HPCS_URL:${url}"
      "HPCS_IAM_API_KEY:${api_key}"
    )
    if [[ -n "${key_id}" ]]; then
      pairs+=("HPCS_KEY_ID:${key_id}")
    fi

    for var_pair in "${pairs[@]}"; do

      local var_name="${var_pair%%:*}"
      local var_value="${var_pair#*:}"

      if grep -q "^${var_name}=" "${ENV_FILE}"; then
        # Replace existing (including empty) value
        sed -i.bak "s|^${var_name}=.*|${var_name}=${var_value}|" "${ENV_FILE}"
        updated=true
      elif grep -q "^#.*${var_name}=" "${ENV_FILE}"; then
        # Uncomment and set
        sed -i.bak "s|^#.*${var_name}=.*|${var_name}=${var_value}|" "${ENV_FILE}"
        updated=true
      else
        echo "${var_name}=${var_value}" >>"${ENV_FILE}"
      fi
    done

    rm -f "${ENV_FILE}.bak"
    log_info "Updated ${ENV_FILE} with detected HPCS values."
    log_info "Update ${ENV_FILE} with KP values(if not done already) before proceeding with migration."
  else
    cat >"${ENV_FILE}" <<EOF
# Auto-generated by migrate-odf.sh
HPCS_INSTANCE_ID=${instance_id}
HPCS_IAM_API_KEY=${api_key}
HPCS_KEY_ID=${key_id}
HPCS_URL=${url}

# Key Protect (destination) — fill these in manually
KP_INSTANCE_ID=
KP_IAM_API_KEY=
KP_KEY_ID=
KP_URL=
EOF
    log_info "Created ${ENV_FILE} with detected HPCS values."
    log_info "Fill in the KP_* values before running the migration."
  fi
}

# --- Run a phase and abort on failure ---

run_phase() {
  local script="$1" phase="$2"
  log_info ">>> ${script} ${phase}"
  "${SCRIPT_DIR}/${script}" "${phase}"
}

# --- Migration ---

migrate() {
  log_info "Starting full ODF KMS migration: HPCS -> Key Protect"
  echo ""

  detect_hpcs_config

  # Reload .env in case we just wrote to it
  load_env

  # Verify KP vars are set before starting
  if [[ -z "${KP_INSTANCE_ID:-}" || -z "${KP_IAM_API_KEY:-}" || -z "${KP_URL:-}" ]]; then
    log_fatal "KP_INSTANCE_ID, KP_IAM_API_KEY, and KP_URL must be set in .env or environment."
  fi

  echo ""
  log_info "=== Migration Plan ==="
  log_info "  1. CSI volumes  — migrate-csi.sh   (pre, phases 1-5, post)"
  log_info "  2. OSD keys     — migrate-osd.sh   (phases 1-6)"
  log_info "  3. NooBaa key   — migrate-noobaa.sh (phases 1-6)"
  echo ""

  # Run prerequisite checks for all scripts before starting
  log_info "Running prerequisite checks..."
  run_phase migrate-csi.sh check
  run_phase migrate-osd.sh check
  run_phase migrate-noobaa.sh check

  read -rp "Start migration? (yes/no): " confirm
  if [[ "${confirm}" != "yes" ]]; then
    log_info "Migration aborted by user."
    exit 0
  fi

  # ---- 1. CSI volumes ----
  log_info "============================================"
  log_info "=== Step 1/3: CSI Volume Migration       ==="
  log_info "============================================"

  run_phase migrate-csi.sh pre
  run_phase migrate-csi.sh phase1
  run_phase migrate-csi.sh phase2
  run_phase migrate-csi.sh phase3
  run_phase migrate-csi.sh phase4
  run_phase migrate-csi.sh phase5
  run_phase migrate-csi.sh post

  log_info "CSI migration complete."
  echo ""

  # ---- 2. OSD keys ----
  log_info "============================================"
  log_info "=== Step 2/3: OSD Key Migration          ==="
  log_info "============================================"

  run_phase migrate-osd.sh phase1
  run_phase migrate-osd.sh phase2
  run_phase migrate-osd.sh phase3
  run_phase migrate-osd.sh phase4
  run_phase migrate-osd.sh phase5
  run_phase migrate-osd.sh phase6

  log_info "OSD migration complete."
  echo ""

  # ---- 3. NooBaa key ----
  log_info "============================================"
  log_info "=== Step 3/3: NooBaa Key Migration       ==="
  log_info "============================================"

  run_phase migrate-noobaa.sh phase1
  run_phase migrate-noobaa.sh phase2
  run_phase migrate-noobaa.sh phase3
  run_phase migrate-noobaa.sh phase4
  run_phase migrate-noobaa.sh phase5
  run_phase migrate-noobaa.sh phase6

  log_info "NooBaa migration complete."
  echo ""

  log_info "============================================"
  log_info "=== Full ODF KMS migration complete      ==="
  log_info "============================================"
  log_info "All three subsystems have been migrated to Key Protect."
  log_info "Run individual cleanup commands when confident the migration is stable:"
  log_info "  ${SCRIPT_DIR}/migrate-osd.sh cleanup"
  log_info "  ${SCRIPT_DIR}/migrate-noobaa.sh cleanup"
}

# --- Main ---

usage() {
  cat <<EOF
Usage: $0 <command>

Orchestrate the full ODF KMS migration from IBM HPCS to IBM Key Protect.
Auto-detects HPCS configuration from the cluster and runs all three migration
scripts in the correct order.

Commands:
  migrate     Run the full migration (CSI -> OSD -> NooBaa)
  detect      Auto-detect HPCS config and write to .env (without migrating)

Migration order:
  1. CSI volumes  — migrate-csi.sh   (pre, phases 1-5, post)
  2. OSD keys     — migrate-osd.sh   (phases 1-6)
  3. NooBaa key   — migrate-noobaa.sh (phases 1-6)

Environment variables:
  See .env.example for the full list. HPCS values are auto-detected from the
  cluster. KP values must be provided.
EOF
}

main() {
  local cmd="${1:-}"
  case "${cmd}" in
  migrate) migrate ;;
  detect) detect_hpcs_config ;;
  *)
    usage
    exit 1
    ;;
  esac
}

load_env

main "$@"
